apiVersion: v1
kind: Service
metadata:
  name: persistence-service-ref-app
  labels:
    app: ps-ref-app
    service: persistence-service-ref-app
spec:
  ports:
    - port: 9090
      targetPort: 9090
      name: ps-ref-app
  selector:
    app: ps-ref-app
    service: persistence-service-ref-app
  type: LoadBalancer